field_mappings:
  # field_mappings are prioritised from last to first in order to deal with the duplicate field names for vario altitude
  # and GPS Elevation. GPS Elevtion should always be present but vario altitude (which would occur first) is optional.
  "Alt(m)":
    - "Vario Alt(m)"
    - "GPS Alt(m)"
displayed_fields:
  - "Index"
  - "Height above Ground (m)"
  - "Ptch(rad)"
  - "Roll(rad)"
  - "Yaw(rad)"
  - "Rud"
  - "Ele"
  - "Thr"
  - "Ail"
  - "1RSS(dB)"
  - "2RSS(dB)"
  - "RQly(%)"
  - "RSNR(dB)"
  - "ANT"
  - "RFMD"
  - "TPWR(mW)"
  - "TRSS(dB)"
  - "TQly(%)"
  - "TSNR(dB)"
  - "RxBt(V)"
  - "Bat(%)"
  - "VSpd(m/s)"
  - "Vario Alt(m)"
  - "Date"
  - "Time"
  - "GPS"
  - "GSpd(kmh)"
  - "Hdg(°)"
  - "GPS Alt(m)"
  - "Sats"
  - "Coordinates"
  - "Interpolated"
  - "P1"
  - "P2"
  - "SA"
  - "SB"
  - "SC"
  - "SD"
  - "SE"
  - "SF"
  - "LSW"
  - "TxBat(V)"
xyzLimit:  # Maximum distance from median value for longitude, latitude and elevation
  - 0.02
  - 0.02
  - 500
xyzDeltaLimit:  # Maximum distance per second between for points for longitude, latitude and elevation
  - 0.0005
  - 0.0005
  - 250
xyzRounding:  # Number of decimal places for longitude, latitude and elevation
  - 6
  - 6
  - 0
validSatRange:  # Min and max number of satellites for a valid coordinate
  - 4
  - 50
line_style:  # Style for flight path
  color: "99009999"  # 50% simplekml.Color.yellow
  width: 1
point_style:  # Style for telemetry data points
  label_points: false
  icon_scale: 0.5
  icon_color: "ff008000"  # simplekml.Color.green
  interp_icon_color: "ff0000ff"  # simplekml.Color.red
  icon_href: "http://maps.google.com/mapfiles/kml/shapes/placemark_circle.png"
  label_color: "ff00ffff"  # simplekml.Color.yellow
  label_scale: 0.5
